# Generated by Django 3.2.7 on 2021-09-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
